name: Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: preview-build
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bdeploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Railway Preview Deploy
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: staging
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}
          cleanup: 'true'
